BASKETBALL LAUNCHER: Ball_Launcher_Controller/Core/Src/main.c File Reference
main.c File Reference
Main program body.
#include "main.h"
#include "mpu6050.h"
#include <stdio.h>
#include <string.h>
Functions
void SystemClock_Config (void)
System Clock Configuration.
int main (void)
The application entry point.
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
I2C_HandleTypeDef hi2c1
UART_HandleTypeDef huart1
UART_HandleTypeDef huart2
int32_t X = 0
int32_t Y = 0
int32_t Z = 0
uint16_t imuStat = 0
uint16_t esc = 0
uint16_t lock = 0
Detailed Description
Main program body.
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file main.c.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
Referenced by SystemClock_Config().
main()
int main (void)
The application entry point.
Return values
int
{
  /* USER CODE BEGIN 1 */
  /* USER CODE END 1 */
  /* MCU Configuration--------------------------------------------------------*/
  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();
  /* USER CODE BEGIN Init */
  /* USER CODE END Init */
  /* Configure the system clock */
  SystemClock_Config();
  /* USER CODE BEGIN SysInit */
  /* USER CODE END SysInit */
  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_I2C1_Init();
  MX_USART1_UART_Init();
  MX_USART2_UART_Init();
  /* USER CODE BEGIN 2 */
  MPU6050 imu;
  imuStat = mpu6050_init(&imu, &hi2c1);
  mpu6050_calibrate(&imu);
  /* USER CODE END 2 */
  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
//  char buffer[100];
  while (1)
  {
      HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, imuStat);
      HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, esc);
      HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, lock);
      mpu6050_update(&imu, 1);
      X = mpu6050_get_gX(&imu);
      Y = mpu6050_get_gY(&imu);
      Z = mpu6050_get_gZ(&imu);
      char buffer[100];
      snprintf(buffer, sizeof(buffer), "%ld\t%ld\t%ld\r\n", X, Y, Z);
      HAL_UART_Transmit(&huart1, (uint8_t *)buffer, strlen(buffer), 100);
    /* USER CODE END WHILE */
    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}
References esc, hi2c1, huart1, imuStat, lock, mpu6050_calibrate(), mpu6050_get_gX(), mpu6050_get_gY(), mpu6050_get_gZ(), mpu6050_init(), mpu6050_update(), SystemClock_Config(), X, Y, and Z.
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 25;
  RCC_OscInitStruct.PLL.PLLN = 192;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = 4;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3) != HAL_OK)
  {
    Error_Handler();
  }
}
References Error_Handler().
Referenced by main().
Variable Documentation
esc
uint16_t esc = 0
Referenced by main().
hi2c1
I2C_HandleTypeDef hi2c1
Referenced by main().
huart1
UART_HandleTypeDef huart1
Referenced by main().
huart2
UART_HandleTypeDef huart2
imuStat
uint16_t imuStat = 0
Referenced by main().
lock
uint16_t lock = 0
Referenced by main().
X
int32_t X = 0
Referenced by main().
Y
int32_t Y = 0
Referenced by main().
Z
int32_t Z = 0
Referenced by main().