BASKETBALL LAUNCHER: Ball_Launcher_Controller/Core/Inc/mpu6050.h File Reference
mpu6050.h File Reference
Header for mpu6050.c file. This file contains the common defines of the application.
#include <stdio.h>
#include <stdint.h>
#include "stm32f4xx_hal.h"
Data Structures
struct MPU6050
Struct representing a mpu6050 imu sensor.
Functions
uint16_t mpu6050_init (MPU6050 *imux, I2C_HandleTypeDef *hi2c)
Initializes the MPU6050 sensor.
void mpu6050_calibrate (MPU6050 *imux)
Calibrates the MPU6050 sensor.
void mpu6050_update (MPU6050 *imux, uint16_t dt)
Updates the MPU6050 sensor data.
int16_t mpu6050_get_gX (MPU6050 *imux)
Gets the calibrated X-axis gyroscope data.
int16_t mpu6050_get_gY (MPU6050 *imux)
Gets the calibrated Y-axis gyroscope data.
int16_t mpu6050_get_gZ (MPU6050 *imux)
Gets the calibrated Z-axis gyroscope data.
int32_t mpu6050_get_X (MPU6050 *imux)
Gets the X-axis accelerometer data.
int32_t mpu6050_get_Y (MPU6050 *imux)
Gets the Y-axis accelerometer data.
int32_t mpu6050_get_Z (MPU6050 *imux)
Gets the Z-axis accelerometer data.
Detailed Description
Header for mpu6050.c file. This file contains the common defines of the application.
Definition in file mpu6050.h.
Function Documentation
mpu6050_calibrate()
void mpu6050_calibrate (MPU6050 * imux)
Calibrates the MPU6050 sensor.
Parameters
imux Pointer to the MPU6050 structure.
{
    int16_t gX_total = 0;
    int16_t gY_total = 0;
    int16_t gZ_total = 0;
    const int num_samples = 10;
    for (int i = 0; i < num_samples; i++) {
        mpu6050_update(imux, 10);
        gX_total += imux->gX;
        gY_total += imux->gY;
        gZ_total += imux->gZ;
        HAL_Delay(10);
    }
    imux->gX_offset = gX_total / num_samples;
    imux->gY_offset = gY_total / num_samples;
    imux->gZ_offset = gZ_total / num_samples;
    imux->X = 0;
    imux->Y = 0;
    imux->Z = 0;
}
References MPU6050::gX, MPU6050::gX_offset, MPU6050::gY, MPU6050::gY_offset, MPU6050::gZ, MPU6050::gZ_offset, mpu6050_update(), MPU6050::X, MPU6050::Y, and MPU6050::Z.
Referenced by main().
mpu6050_get_gX()
int16_t mpu6050_get_gX (MPU6050 * imux)
Gets the calibrated X-axis gyroscope data.
Parameters
imux Pointer to the MPU6050 structure.
Returns
int16_t Calibrated X-axis gyroscope data.
{
    return (imux->gX - imux->gX_offset);
}
References MPU6050::gX, and MPU6050::gX_offset.
Referenced by main().
mpu6050_get_gY()
int16_t mpu6050_get_gY (MPU6050 * imux)
Gets the calibrated Y-axis gyroscope data.
Parameters
imux Pointer to the MPU6050 structure.
Returns
int16_t Calibrated Y-axis gyroscope data.
{
    return (imux->gY - imux->gY_offset);
}
References MPU6050::gY, and MPU6050::gY_offset.
Referenced by main().
mpu6050_get_gZ()
int16_t mpu6050_get_gZ (MPU6050 * imux)
Gets the calibrated Z-axis gyroscope data.
Parameters
imux Pointer to the MPU6050 structure.
Returns
int16_t Calibrated Z-axis gyroscope data.
{
    return (imux->gZ - imux->gZ_offset);
}
References MPU6050::gZ, and MPU6050::gZ_offset.
Referenced by main().
mpu6050_get_X()
int32_t mpu6050_get_X (MPU6050 * imux)
Gets the X-axis accelerometer data.
Parameters
imux Pointer to the MPU6050 structure.
Returns
int32_t X-axis accelerometer data.
{
    return imux->X/1000;
}
References MPU6050::X.
mpu6050_get_Y()
int32_t mpu6050_get_Y (MPU6050 * imux)
Gets the Y-axis accelerometer data.
Parameters
imux Pointer to the MPU6050 structure.
Returns
int32_t Y-axis accelerometer data.
{
    return imux->Y/1000;
}
References MPU6050::Y.
mpu6050_get_Z()
int32_t mpu6050_get_Z (MPU6050 * imux)
Gets the Z-axis accelerometer data.
Parameters
imux Pointer to the MPU6050 structure.
Returns
int32_t Z-axis accelerometer data.
{
    return imux->Z/1000;
}
References MPU6050::Z.
mpu6050_init()
uint16_t mpu6050_init (MPU6050 * imux, I2C_HandleTypeDef * hi2c)
Initializes the MPU6050 sensor.
Parameters
imux Pointer to the MPU6050 structure.
hi2c Pointer to the I2C handle structure.
Returns
uint16_t Returns 1 if initialization is successful, otherwise 0.
{
    imux->hi2c = hi2c;
    imux->gX = 0;
    imux->gY = 0;
    imux->gZ = 0;
    imux->gX_offset = 0;
    imux->gY_offset = 0;
    imux->gZ_offset = 0;
    imux->X = 0;
    imux->Y = 0;
    imux->Z = 0;
    imux->addr = 0x68;
    imux->status = HAL_I2C_IsDeviceReady(imux->hi2c, (imux->addr << 1), 1, 100);
    if (imux->status == HAL_OK) {
            uint8_t data[2];
            data[0] = 0x00;
            HAL_I2C_Mem_Write(imux->hi2c, (imux->addr << 1), 0x6B, I2C_MEMADD_SIZE_8BIT, data, 1, 100);
            HAL_I2C_Mem_Write(imux->hi2c, (imux->addr << 1), 0x1B, I2C_MEMADD_SIZE_8BIT, data, 1, 100);
            return 1;
    }
    else{
        return 0;
    }
}
References MPU6050::addr, MPU6050::gX, MPU6050::gX_offset, MPU6050::gY, MPU6050::gY_offset, MPU6050::gZ, MPU6050::gZ_offset, MPU6050::hi2c, MPU6050::status, MPU6050::X, MPU6050::Y, and MPU6050::Z.
Referenced by main().
mpu6050_update()
void mpu6050_update (MPU6050 * imux, uint16_t dt)
Updates the MPU6050 sensor data.
Parameters
imux Pointer to the MPU6050 structure.
dt Time interval in milliseconds.
{
    uint8_t data[6];
    int16_t gx, gy, gz;
    imux->status = HAL_I2C_Mem_Read(imux->hi2c, (imux->addr << 1), 0x43, I2C_MEMADD_SIZE_8BIT, data, 6, 100);
    if (imux->status == HAL_OK) {
        gx = (int16_t)((data[0] << 8) | data[1]);
        gy = (int16_t)((data[2] << 8) | data[3]);
        gz = (int16_t)((data[4] << 8) | data[5]);
        imux->gX = gx / 131;
        imux->gY = gy / 131;
        imux->gZ = gz / 131;
        imux->X += (mpu6050_get_gX(imux) * dt);
        imux->Y += (mpu6050_get_gY(imux) * dt);
        imux->Z += (mpu6050_get_gZ(imux) * dt);
    }
}
References MPU6050::addr, MPU6050::gX, MPU6050::gY, MPU6050::gZ, MPU6050::hi2c, mpu6050_get_gX(), mpu6050_get_gY(), mpu6050_get_gZ(), MPU6050::status, MPU6050::X, MPU6050::Y, and MPU6050::Z.
Referenced by main().